name: FVTT Release Packager
on:
  release:
    types: [released]

jobs:
  create-release-package:
    runs-on: ubuntu-latest
    steps:
      - uses: VTTAssets/fvtt-release-packager@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
